name: Build and Test

on:
  push:
    branches:
      - main
      - '*'
  pull_request:
    branches:
      - main
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FH_TOKEN: ${{ secrets.FH_TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: stable

    - name: Install make
      run: sudo apt-get install make

    - name: Test and Build
      run: make gh-workflow

